global:
  scrape_interval: 10s
  scrape_timeout: 9s

scrape_configs:
  - job_name: assigner
    metrics_path: /metrics
    static_configs:
      - targets: ["assigner:8080"]

# Ну и сюда же еще node-exporter вообще в идеале, но это как будто уже оверкилл для тестового задания...